url: https://yfidoc.github.io
baseurl: /Codify/

# Site settings
title: Codify
email: support@digifaire.com
description: "Codify is a coding club, and provides coding services to clients."


# Team names, titles and social links
people:
- name: Arianne Ghislaine Rull 
  pic: 1
  position: Founder
  

- name: Raju Basumatary
  pic: 2
  position: Founder 
  

- name: Open
  pic: 3
  position: Chief Executive Officer
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Toronto

# Build settings
markdown: kramdown
permalink: pretty
